### ISSUE TITLE
照相机方向有问题

### ISSUE THREAD

**Issue by Wangpw123** [hnlbxb2004/ZxingSupport#3]
照相机拍摄的照片和扫描框显示的角度不同,相差90度.这样在用户调整扫描方向的时候就有奇怪的体验.请作者能发现并修改一下这个问题.急用..

**Comment by hnlbxb2004** [comment]
@Wangpw123 你用的什么版本？版本号给我发一下。我看下。还有机型等。

**Comment by hnlbxb2004** [comment]
@Wangpw123 我检查了以下。有可能你用的我之前的一个版本的。之前有个版本是有问题的。你用最新的版本应该没问题。我重提提交了一个版本。测试了好多台手机都没有什么问题。暂时先关闭了。
