### ISSUE TITLE
在Fragment中调用onPause再调用onResume不正常工作

### ISSUE THREAD

**Issue by JoneXia** [hnlbxb2004/ZxingSupport#4]
在一个FragmentActivity中使用ScanFragment开始扫描，扫描到结果后切换到一个ResultFragment，再返回到ScanFragment中时不能自动扫描。

原因是在QRCodeSupport的onResume中，surfaceHolder.addCallback不会触发调用surfaceChanged方法，只有第一次初始化的时候才会被调用。

我目前是重写了一个QRCodeSupport来解决这个问题。

**Comment by hnlbxb2004** [comment]
新版本已修改此问题。
